### ISSUE TITLE
安装后，不能正确识别新建的markdown文件，note status命令也无效

### ISSUE THREAD

**Issue by TheKiteRunning** [Jefffffrey/smart-note#1]
看到您的作品太开心了，立马试用了一下。

遇到问题如图，简单描述就是：

1. 文件没有找到，用sublimetext写的，应该是utf-8
2. `state`是不是乔错了
3. 不知道您的软件可不可以跟资源管理器directory opus的关键词或者星级功能联合使用。

![image](https://cloud.githubusercontent.com/assets/24802332/23448162/48f3d874-fe8a-11e6-8b15-a953f912ff9e.png)

![image](https://cloud.githubusercontent.com/assets/24802332/23448304/174c2438-fe8b-11e6-9a0d-ae8952ed05ec.png)

**Comment by Jefffffrey** [comment]
谢谢反馈，打字错误已修正。
Directory Opus插件开发比较复杂，暂时不会提供。
